config/routes.rb
Rails.application.routes.draw do

  root "pages#home"
  get "resume" => "pages#resume"
  get "resume_pdf" => "pages#resume_pdf"
  get ".well-known/keybase.txt" => "pages#keybase"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def resume
  end

  def resume_pdf
    send_file("public/Secord_Resume.pdf", :type => "application/pdf")
  end

  def keybase
    render file: "public/keybase.txt", layout: false, content_type: 'text/plain'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
Painstakingly handcrafted somewhere in the US by <%= link_to 'Michael Secord', 'http://github.com/gizmokid2005' %>
<span class="glyphicon glyphicon-copyright-mark"></span> 2020

app/views/layouts/_header.html.erb
<div class="jumbotron center">
  <h2>MICHAEL SECORD</h2>
  <small>(616) 284-1820 • michael@gizmokid2005.com • <%= link_to "LinkedIn", "https://linkedin.com/in/michael-gizmokid2005" %></small>
</div>
<hr class="seven">

app/views/layouts/_nav.html.erb
<nav class="navbar navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Welcome", root_path, class: "navbar-brand"%>
      <p class="navbar-text">
        Have a wonderful <%= Time.zone.now.strftime("%A") %>!
      </p>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Resume", resume_path %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Michael Secord</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>

  <div id="wrap">
    <%= render 'layouts/nav' %>
    <div class="container">
      <%= render 'layouts/header' %>
      <%= yield %>
    </div>
  </div>

  <div id="footer">
    <div class="container center">
      <p class="text-muted"><%= render 'layouts/footer' %></p>
    </div>
  </div>

  </body>
</html>

app/views/pages/home.html.erb
<div class="text-center">
  <%= link_to "Resume", resume_path, :class => "btn btn-lg btn-success" %>
</div>

app/views/pages/letsencrypt.text.erb
==================================================================
https://keybase.io/gizmokid2005
--------------------------------------------------------------------

I hereby claim:

* I am an admin of https://michaelsecord.com
* I am gizmokid2005 (https://keybase.io/gizmokid2005) on keybase.
* I have a public key with fingerprint 7E26 EC9E EB4E EFB2 8FEE  8AF1 FF68 E251 F5D2 2982

To do so, I am signing this object:

{
"body": {
"key": {
"eldest_kid": "01206e2069f9e9fbd573e841029653916edaa38df42493a85dafa74427b6f19e58550a",
"fingerprint": "7e26ec9eeb4eefb28fee8af1ff68e251f5d22982",
"host": "keybase.io",
"key_id": "ff68e251f5d22982",
"kid": "01012b801ceec1993fbf4737843eadb92f8fcfc6fa6e742180314cc0057799d2924d0a",
"uid": "f475d9ef564670b5caf9d9968e30f519",
"username": "gizmokid2005"
},
"service": {
"hostname": "michaelsecord.com",
"protocol": "https:"
},
"type": "web_service_binding",
"version": 1
},
"ctime": 1507053314,
"expire_in": 157680000,
"prev": "e158042e343d61ac78eec600fbb1f6d5bf48e9527199fc101fb9326645f8abd2",
"seqno": 34,
"tag": "signature"
}

which yields the signature:

-----BEGIN PGP MESSAGE-----
Version: Keybase OpenPGP v2.0.74
Comment: https://keybase.io/crypto

yMN2AnicbVJ9TJVVHL6gIsJokiOaVNorjCA+3u/3PReHSdQyxSLky6Dr+3HO5QXu
feG+l+8QhaGYApuppXwkMEdjFfKVsPUh0MCsFSBStEZTMBdGF02wOVedS/pfZzs7
O+f3PM/vOc9+X/mtMvl4/JN1PXFpIqzS45vBlgJT+pXvPcsIWVdLCHMZkQNXDpir
QsNpydFUwkyQFE3yEG+AAARIVjmBgSJLkTTgOQZQPFQliRFVxNIsYCSRUyUkCSxL
CzKPKAA5keNIiYggkGa3QkeeQ7M7sawAaR4qAEKZhRDJtIggFCVEIcSLkOYoxKk0
DUQaE7N0w83A5mTJgFGajt/wxbJi73/wj3xj57JIUgqECgUAg2TECowgsgyUVBnQ
SEQKUngk8VBgaUokGYpVFJLkBAEAlQY0q674LvivDytwKoCI41leIGVOkRBQAcDN
GRJxFHADDeiwSzaI0Vat1KZjHzSWI8ojCFwp1BToDtf9m4com6ZkSTDXgIruUKMU
3YZF8hy6U1f0XFzOcjrzDLOb7izJc+OLoGx5qGSRNbuKA8WMQugwNN1OmCmMVJya
W5riSIHkGPyjCAIW52kOaNHcCE7gRRIvdx9YiCUhxYkkS0OGZVSekhRBxGnxJIlk
mUK8yuHMRAg4WsAJIgVHimTA0DzPckiUZNUdtwHz7TphZnArp2TFmoZmtUvOAgck
yocGM1abPHxMXms83ZNm8lm3/tH8te5ebzo0cimuaubnXYS2nDpx5WDVcGZk/2ut
SyGX9yQ9iDx3xBb+XNS22dcXRkPuqRd+Ty1O37j4gxHvICbvakkDbyQ/4Wpo+yI+
8FRd39bo87XVv0Q+A1u6qMC9W/TLZNytnjn/7Ul9QeA0s/F2yqU0/dBi6PyB+M73
a+NCt87VHfnwo64N4fPBeWPZrj8Z13FXX+PTlcKX/eMdq7enhDTNBocZDRGdV/sn
zyTWNVYvbYt6XhqnFtnw+zGv3gto7I6ydH62fKf579F98eUv/RRwInQm4dOm7KCB
2Kyx3aVF/tP70vJv+j5oSzWmXuic9d5xe3O65T3Pst5P/I8OnT9qg41jCZPvxu6f
Sl1/tuVjz2cHRkorvGJGXg4u7vrjKd8FUDUX8hhHAL7urY7JwKRT5cP9NeNCtFdY
d9Nf+mjHscy1fpW9yai352K03LEpY+fQt8ktG6av/TqWsMN19qaVePL+UnmZz0Iw
EXZyutvRbBvyNec7Cu8YphsgO+5ge+bnm/ccNk/tJ9qqh63JU/S69uYAerDJPFJ8
xtV7tzbF05oWueu7d6b2kq1vNlb0BLnm53fWF6+qe3zxx8SrbV/LLuuatYsnjJhj
rxyvyo3l071NiYcPdJxOyQktCHiRmr52IaPee7Gi5rflyS6/LSju+smaiZlzm3wn
Yupbht4uulFb0mB3URUfXBxtv/UvKEbGiw==
=RwsF
-----END PGP MESSAGE-----

And finally, I am proving ownership of this host by posting or
appending to this document.

View my publicly-auditable identity here: https://keybase.io/gizmokid2005

==================================================================

app/views/pages/resume.html.erb
<strong><h3>SQL DEVELOPER</h3></strong>
<hr class="one">
<div class="row">
  <div class="col-md padleft1">Analytical, detail-oriented business professional with demonstrated success in identifying, designing, and implementing internal process improvements and optimizing data delivery. Understands data flow, troubleshoots data issues and responds to requests for data in a timely manner. Knowledge of data integration, SQL programming, ETL and data warehouse concepts and processes. Key competencies:
  </div>
</div>
<br/>
<div class="row">
  <div class="col-md-4 col-md-offset-2">
    <ul>
      <li>SQL Server Developer</li>
      <li>Data Sharing / Warehousing</li>
      <li>Data Analysis</li>
      <li>Quality / Continuous Improvement</li>
    </ul>
  </div>
  <div class="col-md-4">
    <ul>
      <li>Enterprise Software Implementation</li>
      <li>Data Conversion</li>
      <li>Project Implementations</li>
      <li>Leadership / Training / Collaborator</li>
    </ul>
  </div>
</div>
<strong><h3>EXPERIENCE</h3></strong>
<hr class="one">
<div class="row">
  <div class="col-md-10 padleft">
    <strong>Epiq Systems, LLC</strong> -- Remote
  </div>
</div>
<div class="row">
  <div class="col-md-4 padleft2">
    <strong><i>Lead SQL Developer</i></strong>
  </div>
  <div class="col-md-2 col-md-offset-6">
    <strong><i>03/2024 - Present</i></strong>
  </div>
</div>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <ul>
      <li>Developed and maintained ETL procedures according to client specifications and within defined technical standards.</li>
      <li>Developed and maintained database stored procedures, user-defined functions, views, triggers, and other common database objects.</li>
      <li>Wrote custom and ad-hoc SQL queries.</li>
      <li>Used prescribed software development standards, processes, and procedures according to department policies and conventions.</li>
      <li>Supported team as part of escalation path and as expert resource as needed to solve complex issues and requests.</li>
    </ul>
  </div>
</div>
<div class="row">
  <div class="col-md-10 padleft">
    <strong>Epiq Systems, LLC</strong> -- Remote
  </div>
</div>
<div class="row">
  <div class="col-md-4 padleft2">
    <strong><i>Senior SQL Developer</i></strong>
  </div>
  <div class="col-md-2 col-md-offset-6">
    <strong><i>02/2022 - 03/2024</i></strong>
  </div>
</div>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <ul>
      <li>Developed and maintained ETL procedures according to client specifications and within defined technical standards.</li>
      <li>Developed and maintained database stored procedures, user-defined functions, views, triggers, and other common database objects.</li>
      <li>Wrote custom and ad-hoc SQL queries.</li>
      <li>Used prescribed software development standards, processes, and procedures according to department policies and conventions.</li>
      <li>Supported team as part of escalation path and as expert resource as needed to solve complex issues and requests.</li>
    </ul>
  </div>
</div>
<div class="row">
  <div class="col-md-10 padleft">
    <strong>Modis</strong> -- Remote
  </div>
</div>
<div class="row">
  <div class="col-md-4 padleft2">
    <strong><i>SQL Developer</i></strong>
  </div>
  <div class="col-md-2 col-md-offset-6">
    <strong><i>12/2020 - 02/2022</i></strong>
  </div>
</div>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <ul>
      <li>Developed and maintained ETL procedures according to client specifications and within defined technical standards.</li>
      <li>Developed and maintained database stored procedures, user-defined functions, views, triggers, and other common database objects.</li>
      <li>Wrote custom and ad-hoc SQL queries.</li>
      <li>Used prescribed software development standards, processes, and procedures according to department policies and conventions.</li>
    </ul>
  </div>
</div>
<div class="row">
  <div class="col-md-10 padleft">
    <strong>Boot Barn</strong> -- Irvine, CA
  </div>
</div>
<div class="row">
  <div class="col-md-4 padleft2">
    <strong><i>CRM Data Analyst</i></strong>
  </div>
  <div class="col-md-2 col-md-offset-6">
    <strong><i>08/2018 – 06/2020</i></strong>
  </div>
</div>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <ul>
      <li>Responsible for managing direct mail lists, analyzing ROI, segmentation and making recommendations.</li>
      <li>Performed as-needed on-going data analysis to support ad-hoc and standard business requests while maintaining data integrity.</li>
      <li>Developed and maintained SQL infrastructure (tables, stored procedures, functions, views, indexes) to managed processes for reporting and analysis.</li>
      <li>Managed ETL processes as needed for data sharing between services and systems for analysis and integration.</li>
      <li>Worked to provide continuous improvement in CRM data quality and infrastructure.</li>
    </ul>
  </div>
</div>
<div class="row">
  <div class="col-md-10 padleft">
    <strong>Secord Labs</strong> -- Long Beach, CA
  </div>
</div>
<div class="row">
  <div class="col-md-4 padleft2">
    <strong><i>Owner</i></strong>
  </div>
  <div class="col-md-2 col-md-offset-6">
    <strong><i>10/2016 - 08/2018</i></strong>
  </div>
</div>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <ul>
      <li>Served as part of the implementation and project teams, participating in client contact, configuration, data migration, development, professional services.</li>
      <li>Participated in on-site analysis and trainings with clients; member of internal teams during the implementation process.</li>
      <li>Assisted in creating/executing test plans for workflow and data validation.</li>
      <li>Managed and created reports using in-house reporting tools & SQL queries in MSSQL.</li>
      <li>Created ETL data migration plans and scripts to migrate from old systems & flat files to MSSQL databases utilizing SQL Server tools, Excel and CRUD methodologies as needed.</li>
    </ul>
  </div>
</div>
<div class="row">
  <div class="col-md-10 padleft">
    <strong>BKD, LLP</strong> -- Kansas City, MO
  </div>
</div>
<div class="row">
  <div class="col-md-4 padleft2">
    <strong><i>Senior Consultant</i></strong>
  </div>
  <div class="col-md-2 col-md-offset-6">
    <strong><i>03/2015 - 10/2016</i></strong>
  </div>
</div>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <ul>
      <li>Worked closely with all project leads as well as the entire project team to ensure all deliverables were completed and delivered on time, in scope and in their entirety.</li>
      <li>Assisted in creating/executing test plans for workflow and data validation.</li>
      <li>Performed ETL operations on flat file extracted data, including cleansing and data mapping, implementing CRUD as needed via SQL Server tools, Excel, Access, and other tools.</li>
      <li>Supported multiple concurrent implementations.</li>
    </ul>
  </div>
</div>
<div class="row">
  <div class="col-md-10 padleft">
    <strong>Crystal Flash</strong> -- Lowell, MI
  </div>
</div>
<div class="row">
  <div class="col-md-4 padleft2">
    <strong><i>SQL DBA</i></strong>
  </div>
  <div class="col-md-2 col-md-offset-6">
    <strong><i>08/2014 - 02/2015</i></strong>
  </div>
</div>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <ul>
      <li>Managed SQL Server infrastructure, performance, and maintenance.</li>
      <li>Created reports using in-house reporting tools & SQL queries in MSSQL.</li>
      <li>Converted current Access databases/programs to MSSQL Server using ETL and CRUD methodologies utilizing SQL Server SSIS and import tools.</li>
    </ul>
  </div>
</div>
<div class="row">
  <div class="col-md-10 padleft">
    <strong>Rutherford & Associates</strong> -- Holland, MI
  </div>
</div>
<div class="row">
  <div class="col-md-4 padleft2">
    <strong><i>Business Support Analyst</i></strong>
  </div>
  <div class="col-md-2 col-md-offset-6">
    <strong><i>11/2011 - 08/2014</i></strong>
  </div>
</div>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <ul>
      <li>Supported business-critical Route Accounting Software for diverse companies ranging from small pizza distributors to major beer/wine distributors and Coca-Cola bottlers.</li>
      <li>Created reports using in-house reporting tools & SQL queries in MSSQL.</li>
      <li>Performed data extraction, validation, and conversions utilizing ETL and CRUD processes using SQL Server built-in tools, Monarch Pro, Excel, Access and other tools as needed.</li>
      <li>Conducted on-site and remote software training and support for both new and existing customers.</li>
      <li>Trained internal employees on new software features.</li>
      <li>Consultation on business processes relating to route accounting.</li>
    </ul>
  </div>
</div>
<div class="row">
  <div class="col-md-10 padleft">
    <strong>Summit Training Source</strong> -- Grand Rapids, MI
  </div>
</div>
<div class="row">
  <div class="col-md-4 padleft2">
    <strong><i>Technical Specialist/QA Specialist</i></strong>
  </div>
  <div class="col-md-2 col-md-offset-6">
    <strong><i>06/2011 - 11/2011</i></strong>
  </div>
</div>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <ul>
      <li>Provided hardware and software support for internal users.</li>
      <li>Supported internally-developed web application over the phone, by email & by remote assistance.</li>
      <li>Assisted in creating QA guidelines and policies for ensuring consistent testing of software.</li>
      <li>Designed and implemented automation of repetitive tasks leading to a 25% increase in efficiency.</li>
      <li>Ran ad-hoc SQL scripts and queries to support clients, internal and external, as well as the internal development team.</li>
    </ul>
  </div>
</div>
<div class="row">
  <div class="col-md-10 padleft">
    <strong>The Iserv Company</strong> -- Grand Rapids, MI
  </div>
</div>
<div class="row">
  <div class="col-md-4 padleft2">
    <strong><i>IMS Assistant</i></strong>
  </div>
  <div class="col-md-2 col-md-offset-6">
    <strong><i>03/2008 - 06/2011</i></strong>
  </div>
</div>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <ul>
      <li>Ensured integrity of data warehouse (Oracle DB) and SQL/ETL scripts/crons on a daily basis.</li>
      <li>Performed monthly test billing & audit and monitored & completed monthly production billing.</li>
      <li>Support data warehouse client application (Crystal Reports 7).</li>
      <li>Created and ran various SQL queries and scripts.</li>
    </ul>
  </div>
</div>
<div class="row">
  <div class="col-md-4 padleft2">
    <strong><i>Data Analyst</i></strong>
  </div>
  <div class="col-md-2 col-md-offset-6">
    <strong><i>06/2007 - 03/2008</i></strong>
  </div>
</div>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <ul>
      <li>Performed analysis, cleansing, and loading (ETL) of acquired companies' billing systems upping efficiency in the process by 20%.</li>
    </ul>
  </div>
</div>
<div class="row">
  <div class="col-md-4 padleft2">
    <strong><i>Customer Support</i></strong>
  </div>
  <div class="col-md-2 col-md-offset-6">
    <strong><i>03/2006 - 01/2009</i></strong>
  </div>
</div>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <ul>
      <li>Efficiently handled billing/technical issues and internal order processing for new/existing customers.</li>
    </ul>
  </div>
</div>
<strong><h3>PROFESSIONAL DEVELOPMENT</h3></strong>
<hr class="one">
<div class="row">
  <div class="col-md padleft1">
    Accounting/CIS Courses completed. (Baker College)
  </div>
</div>
<strong><h3>TECHNICAL</h3></strong>
<hr class="one">
<div class="row">
  <div class="col-md padleft1">
    T-SQL (Business Intelligence and ETL/CRUD operations in MSSQL, MySQL, Oracle & SQLite)<br/>
    Web/web application development with HTML, CSS, & Ruby on Rails using SVN & GIT; shell scripting
  </div>
</div>
<br/><br/>
<p class="center"><%= link_to "Resume in PDF", "Secord_Resume.pdf", :class => "btn btn-primary" %></p>